### ISSUE TITLE
ignoring .DS_Store

### ISSUE THREAD

**Issue by HughP** [rodrigoalcarazdelaosa/rodrigoalcarazdelaosa.me#1]
You might be interested to follow this https://stackoverflow.com/questions/107701/how-can-i-remove-ds-store-files-from-a-git-repository  I notice that you have a lot of .DS_Store files in your repo.

**Comment by rodrigoalcarazdelaosa** [comment]
Thanks a lot @HughP . I’ll surely get rid of those `.DS_Store` 😉

**Comment by rodrigoalcarazdelaosa** [comment]
Done! Thanks again @HughP.
